namespace :build do
  task :about do
    ruby "build_about.rb"
  end
  task :promises do
    ruby "build_promises.rb"
  end
end

task :default do
  Rake.application.tasks.each do |task|
    task.invoke
  end
end
