namespace :build do
  #task :sanitize do
    #system('find ..
  #end
  task :output_setup do
    ruby "output_setup.rb"
  end
  task :about do
    ruby "build_about.rb"
  end
  task :promises do
    ruby "build_promises.rb"
  end
  task :main do
    ruby "build_main.rb"
  end

  task :all => [:output_setup, :about, :promises, :main]
end

task :setup_mac do
  ruby "setup_mac.rb"
end

desc "Build ayearinoz to test out on your mac"
task :test do
  ENV['site_url'] = 'http://localhost'
  ENV['output_dir'] = '/Library/WebServer/Documents'
  Rake::Task["setup_mac"].invoke
  Rake::Task["build:all"].invoke
end

desc "Build ayearinoz and deploy on the internet"
task :prod do
  ENV['site_url'] = 'http://ayearinoz.holtandkristin.com'
  ENV['output_dir'] = '/tmp/ayearinoz'
  Rake::Task["build:all"].invoke
  #puts "TO COPY TO THE HOSTING PROVIDER:"
  #puts 'lftp -u holtcmto,\'????\' -p 21098 -e \'mirror -c -e -R ' + ENV['output_dir'] + ' public_html/ayearinoz\' sftp://server111.web-hosting.com'
  system('rsync -av --delete /tmp/ayearinoz/ blog:/var/www/html/')
end
